[default]
extend-ignore-re = [
    # spellchecker:disable-line
    "(?Rm)^.*(#|//|--)\\s*spellchecker:disable-line$",
    # spellchecker:<on|off>
    "(?s)(#|//|--)\\s*spellchecker:off.*?\\n\\s*(#|//|--)\\s*spellchecker:on",
]
